# Generated by Django 5.0.1 on 2024-01-22 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episodesource',
            unique_together={('source', 'season', 'episode')},
        ),
        migrations.AlterField(
            model_name='episodesource',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.episode'),
        ),
        migrations.AlterField(
            model_name='episodesource',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.source'),
        ),
        migrations.RemoveField(
            model_name='episodesource',
            name='show',
        ),
    ]
