# Generated by Django 5.0.1 on 2024-01-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_moviesource_valid_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_source',
            new_name='movie_sources',
        ),
    ]
