# Generated by Django 5.0.1 on 2024-01-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_movie_source_movie_movie_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
