# Generated by Django 5.0.1 on 2024-01-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_source_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='show',
            name='is_trending',
        ),
        migrations.RemoveField(
            model_name='show',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='show',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='show',
            name='trending_weight',
        ),
        migrations.RemoveField(
            model_name='show',
            name='weight',
        ),
    ]
