# Generated by Django 5.0.1 on 2024-01-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_show_is_free_remove_show_is_trending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesource',
            old_name='play_link',
            new_name='imdb_link',
        ),
        migrations.RemoveField(
            model_name='show',
            name='sources',
        ),
        migrations.AddField(
            model_name='moviesource',
            name='kinopoisk_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='show_sources',
            field=models.ManyToManyField(related_name='shows', through='content.ShowSource', to='content.source'),
        ),
        migrations.AddField(
            model_name='showsource',
            name='valid_source',
            field=models.BooleanField(default=True),
        ),
    ]
