# Generated by Django 5.0.1 on 2024-01-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_play_link_moviesource_imdb_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='sources',
        ),
        migrations.AddField(
            model_name='season',
            name='season_sources',
            field=models.ManyToManyField(related_name='season', through='content.SeasonSource', to='content.source'),
        ),
    ]
