# Generated by Django 5.0.1 on 2024-01-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_season_sources_season_season_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsource',
            name='valid_source',
            field=models.BooleanField(default=True),
        ),
    ]
