# Generated by Django 5.0.1 on 2024-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_seasonsource_show_alter_seasonsource_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesource',
            name='tmdb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showsource',
            name='tmdb_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
