# Generated by Django 5.0.1 on 2024-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_movie_tmdb_rating_show_tmdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesource',
            name='watch_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showsource',
            name='watch_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
