# Generated by Django 5.0.1 on 2024-01-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_moviesource_watch_link_showsource_watch_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesource',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviesource',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.source'),
            preserve_default=False,
        ),
    ]
