# Generated by Django 5.0.1 on 2024-01-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_moviesource_movie_alter_moviesource_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesource',
            name='valid_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='showsource',
            name='valid_source',
            field=models.BooleanField(default=False),
        ),
    ]
