# Generated by Django 5.0.1 on 2024-01-21 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_moviesource_valid_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.season'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EpisodeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('kinopoisk_link', models.URLField(blank=True, null=True)),
                ('imdb_link', models.URLField(blank=True, null=True)),
                ('valid_source', models.BooleanField(default=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.episode')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.season')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.show')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.source')),
            ],
            options={
                'verbose_name': 'Episode Source',
                'verbose_name_plural': 'Episode Sources',
                'unique_together': {('source', 'show', 'season', 'episode')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_sources',
            field=models.ManyToManyField(related_name='episode', through='content.EpisodeSource', to='content.source'),
        ),
    ]
