# Generated by Django 5.0.1 on 2024-01-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_episode_options_episode_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-created'], 'verbose_name': '7. Episode', 'verbose_name_plural': '7. Episode'},
        ),
        migrations.AlterModelOptions(
            name='episodesource',
            options={'verbose_name': '8. Episode Source', 'verbose_name_plural': '8. Episode Sources'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '1. Movie', 'verbose_name_plural': '1. Movies'},
        ),
        migrations.AlterModelOptions(
            name='moviesource',
            options={'verbose_name': '2. Movie Source', 'verbose_name_plural': '2. Movies Sources'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-created'], 'verbose_name': '5. Season', 'verbose_name_plural': '5. Seasons'},
        ),
        migrations.AlterModelOptions(
            name='seasonsource',
            options={'verbose_name': '6. Season Source', 'verbose_name_plural': '6. Season Sources'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': '3. Show', 'verbose_name_plural': '3. Shows'},
        ),
        migrations.AlterModelOptions(
            name='showsource',
            options={'verbose_name': '4. Show Source', 'verbose_name_plural': '4. Shows Sources'},
        ),
    ]
