# Generated by Django 5.0.1 on 2024-01-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_episode_options_alter_episodesource_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': '0. Source', 'verbose_name_plural': '0. Sources'},
        ),
    ]
