# Generated by Django 5.0.1 on 2024-01-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_source_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='content.show'),
        ),
    ]
