version: "3"

services:
  cinema_app_dev:
    container_name: "cinema_app_dev"
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ../../app/:/cinema/app/
      - ../:/infrastructure/
    command: sh -c "
      python3 manage.py wait_for_db &&
      python3 manage.py migrate &&
      python manage.py initadmin &&

      echo 'yes' | python3 manage.py collectstatic &&

      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - cinema_db_dev
      - redis
      - celery_worker

  cinema_db_dev:
    container_name: "cinema_db_dev"
    image: postgres:15-alpine
    ports:
      - 5400:5432
    volumes:
      - ../../.db/dev:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery_worker:
      container_name: "celery_worker"
      build:
        context: ../../
        dockerfile: Dockerfile
        args:
          - DEV=true
      volumes:
        - ../../app/:/cinema/app/
        - ../:/infrastructure/
      command: sh -c "celery -A config worker --concurrency=10"

      env_file:
        - .env
      depends_on:
        - cinema_db_dev
        - redis
      healthcheck:
        test: ["CMD", "celery", "inspect", "ping"]
        interval: 10s
        timeout: 5s
        retries: 3
